DICTIONARY personas {
    "persona1": {
        "nombre": "Bill",
        "apellido": "Gates"
        "edad": 67,
        "ciudad": "Washington"
        "ocupacion": "Empresario"
        "Telefono": "+1 1111111111"
    }
    "persona2": {
        "nombre": "Elon",
        "apellido": "Musk"
        "edad": 52,
        "ciudad": "Boca Chica"
        "ocupacion": "CEO tesla"
        "Telefono": "+1 2222222222"
    }
    "persona3": {
        "nombre": "Mark",
        "apellido": "Zuckerberg"
        "edad": 39,
        "ciudad": "Palo alto"
        "ocupacion": "CEO Meta"
        "Telefono": "+1 3333333333"
    }
    "persona4": {
        "nombre": "Donald",
        "apellido": "Trump"
        "edad": 77,
        "ciudad": "Palm Beach"
        "ocupacion": "Empresario/politico"
        "Telefono": "+1 4444444444"
    }
    "persona5": {
        "nombre": "Jeff",
        "apellido": "Bezos"
        "edad": 59,
        "ciudad": "Miami"
        "ocupacion": "Empresario"
        "Telefono": "+1 555555555"
    }
}

PRINT("persona 1: ", personas["persona1"])
PRINT("persona 2: ", personas["persona2"])
PRINT("persona 3: ", personas["persona3"])
PRINT("persona 4: ", personas["persona4"])
PRINT("persona 5: ", personas["persona5"])

