STRING a {"Hola mundo!"}

DICTIONARY inventory {"apple": 5, "banana": 3, "orange": 2}
DICTIONARY complex_dict {
    "fruits": {
        "apple": {
            "colour": "red",
            "seed": TRUE
            },
        "banana": {
            "colour": "yellow",
            "seed": TRUE
            }
        },
    "vegetables": {
        "onnion": {
            "colour": "white",
            "seed": FALSE
            },
        "potato": {
            "colour": "red",
            "seed": TRUE
            }
        },
    }
